import Head from 'next/head'
import NavigationBar from '../components/NavigationBar'
import Hero from '../components/Hero'
import About from '../components/About'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationBar/>

      <main className='h-screen overflow-x-hidden overflow-y-scroll'>
        <Hero/>
        <About/>
      
      </main>

      <footer>

      </footer>
    </div>
  )
}
